# Generated by Django 2.2.2 on 2019-07-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190630_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expert',
            field=models.ManyToManyField(through='api.Opinion', to='api.Expert'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.DeleteModel(
            name='FormalProject',
        ),
    ]
