# Generated by Django 2.2.2 on 2019-06-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190629_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enroll_year',
            field=models.IntegerField(null=True),
        ),
    ]
