# Generated by Django 2.2.2 on 2019-07-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190703_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompetitionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_file', models.FileField(max_length=500, upload_to='proje_competition_file/')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Competition')),
            ],
        ),
    ]
