# Generated by Django 2.2.2 on 2019-06-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190629_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('A', '机械与控制'), ('B', '信息技术'), ('C', '数理'), ('D', '生命科学'), ('E', '能源化工'), ('F', '哲学社会科学')], max_length=200, null=True),
        ),
    ]
