# Generated by Django 2.2.2 on 2019-06-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190630_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('机械与控制', 'A'), ('信息技术', 'B'), ('数理', 'C'), ('生命科学', 'D'), ('能源化工', 'E'), ('哲学社会科学', 'F')], max_length=200, null=True),
        ),
    ]
