# Generated by Django 2.2.2 on 2019-07-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190703_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertlist',
            name='field',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
