# Generated by Django 2.2.2 on 2019-06-27 08:00

import api.enum
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190627_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='co_author',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[(api.enum.Category('机械与控制'), '机械与控制'), (api.enum.Category('信息技术'), '信息技术'), (api.enum.Category('数理'), '数理'), (api.enum.Category('生命科学'), '生命科学'), (api.enum.Category('能源化工'), '能源化工'), (api.enum.Category('哲学社会科学'), '哲学社会科学')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='innovation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(blank=True, choices=[(api.enum.Education('college'), 'college'), (api.enum.Education('bachelor'), 'bachelor'), (api.enum.Education('master'), 'master'), (api.enum.Education('doctor'), 'doctor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.CreateModel(
            name='FormalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('education', models.CharField(choices=[(api.enum.Education('college'), 'college'), (api.enum.Education('bachelor'), 'bachelor'), (api.enum.Education('master'), 'master'), (api.enum.Education('doctor'), 'doctor')], max_length=50)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
    ]
