# Generated by Django 2.2.2 on 2019-06-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190630_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formalproject',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Project', 'project'), ('Paper', 'paper')], max_length=10, null=True),
        ),
    ]
