# Generated by Django 2.2.2 on 2019-06-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190627_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='expert',
        ),
        migrations.AddField(
            model_name='formalproject',
            name='expert',
            field=models.ManyToManyField(through='api.Opinion', to='api.Expert'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FormalProject'),
        ),
    ]
