# Generated by Django 2.2.2 on 2019-06-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190630_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
