# Generated by Django 2.2.2 on 2019-07-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190704_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
