# Generated by Django 2.2.2 on 2019-06-30 03:15

import api.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_competition_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('未提交', '未提交'), ('已提交', '已提交'), ('审核中', '审核中'), ('初审通过', '初审通过'), ('初审未通过', '初审未通过'), ('评审中', '评审中'), ('现场答辩', '现场答辩'), ('未进入线下', '未进入线下'), ('一等奖', '一等奖'), ('二等奖', '二等奖'), ('三等奖', '三等奖')], default=api.enum.ProjectStatus('未提交'), max_length=50),
        ),
    ]
