# Generated by Django 2.2.2 on 2019-07-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_expert_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='oral_defense',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='pre_review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
