# Generated by Django 2.2.2 on 2019-07-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190706_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertlist',
            name='status',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
