# Generated by Django 2.2.2 on 2019-07-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190706_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertlist',
            name='competition',
        ),
    ]
