# Generated by Django 2.2.2 on 2019-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_expert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
